/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // A sidebar for the PNPT Prep section
  // 'dirName' must match your folder name exactly, including casing
  pnptSidebar: [{type: 'autogenerated', dirName: 'PNPT_Prep'}],

  // A sidebar for the OSCP Prep section
  oscpSidebar: [{type: 'autogenerated', dirName: 'OSCP_Prep'}],

  // A sidebar for the Cheatsheets section
  cheatsheetsSidebar: [{type: 'autogenerated', dirName: 'cheatsheets'}],
  
  // A sidebar for the Active Directory section
  adSidebar: [{type: 'autogenerated', dirName: 'active_directory'}],
};

export default sidebars;
