/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // A sidebar for the PNPT Prep section
  // 'dirName' must match your folder name exactly, including casing
  osintSidebar: [{type: 'autogenerated', dirName: 'OffSec/osint'}],

  // A sidebar for the OSCP Prep section
  activedirectorySidebar: [{type: 'autogenerated', dirName: 'OffSec/Active Directory'}],

  // A sidebar for the Cheatsheets section
  cheatsheetsSidebar: [{type: 'autogenerated', dirName: 'cheatsheets'}],
  
  // A sidebar for the Active Directory section
  adSidebar: [{type: 'autogenerated', dirName: 'active_directory'}],
};

export default sidebars;
